"""add logo

Revision ID: 06683d1bb042
Revises: af0276064b0f
Create Date: 2022-04-09 12:31:01.282953

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06683d1bb042'
down_revision = 'af0276064b0f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organization', sa.Column('logo', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organization', 'logo')
    # ### end Alembic commands ###
