"""Add phone

Revision ID: af0276064b0f
Revises: b45215e26864
Create Date: 2022-04-09 03:20:06.888634

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af0276064b0f'
down_revision = 'b45215e26864'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organization', sa.Column('phone', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organization', 'phone')
    # ### end Alembic commands ###
