"""add website

Revision ID: b45215e26864
Revises: 3a98e013a6f5
Create Date: 2022-04-09 02:54:55.308311

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b45215e26864'
down_revision = '3a98e013a6f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organization', sa.Column('website', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organization', 'website')
    # ### end Alembic commands ###
